import 'package:flutter/material.dart';
impor

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Login(),
        ]),
      ),
    );
  }
}

class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.50, -0.00),
              end: Alignment(0.50, 1.00),
              colors: [const Color(0xFF6CD6AE), const Color(0xFF16423C)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 287,
                top: 345,
                child: Container(
                  width: 100,
                  height: 100,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                ),
              ),
              Positioned(
                left: 404,
                top: 395,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                  width: 235,
                  height: 391,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/235x391"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 96,
                child: SizedBox(
                  width: 164,
                  child: Text(
                    'Sign In ',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 48,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w800,
                      shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 150,
                child: SizedBox(
                  width: 284,
                  child: Text(
                    'to your Account',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w800,
                      shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -55,
                top: 321,
                child: Container(
                  width: 504,
                  height: 673,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(113),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0xBF000000),
                        blurRadius: 58.20,
                        offset: Offset(0, -6),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 72.19,
                top: 788.98,
                child: Container(
                  width: 250.28,
                  height: 33.02,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 4.59,
                    children: [
                      Text(
                        'Don’t have an account?',
                        style: TextStyle(
                          color: const Color(0xFF6C7278) /* Grey */,
                          fontSize: 9.18,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 1.40,
                          letterSpacing: -0.09,
                        ),
                      ),
                      Text(
                        'Sign Up',
                        style: TextStyle(
                          color: const Color(0xFF4D81E7),
                          fontSize: 9.18,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w600,
                          height: 1.40,
                          letterSpacing: -0.09,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 33.98,
                top: 731.42,
                child: Container(
                  width: 326.49,
                  height: 45.08,
                  padding: const EdgeInsets.symmetric(horizontal: 18.37, vertical: 7.65),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.77,
                        color: const Color(0xFF2B5BD3),
                      ),
                      borderRadius: BorderRadius.circular(7.65),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 7.65,
                    children: [
                      Container(
                        width: 13.86,
                        height: 13.86,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(),
                      ),
                      Text(
                        'Continue with Facebook',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF1A1C1E),
                          fontSize: 10.72,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w600,
                          height: 1.40,
                          letterSpacing: -0.11,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32.33,
                top: 665.76,
                child: Container(
                  width: 328.92,
                  height: 45.99,
                  padding: const EdgeInsets.symmetric(horizontal: 18.37, vertical: 7.65),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.77,
                        color: const Color(0xFF2B5BD3),
                      ),
                      borderRadius: BorderRadius.circular(7.65),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 7.65,
                    children: [
                      Container(
                        width: 13.86,
                        height: 13.86,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(),
                      ),
                      Text(
                        'Continue with Google',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF1A1C1E),
                          fontSize: 10.72,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w600,
                          height: 1.40,
                          letterSpacing: -0.11,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 29.09,
                top: 398,
                child: Text(
                  'Email',
                  style: TextStyle(
                    color: const Color(0xFF6C7278) /* Grey */,
                    fontSize: 9.18,
                    fontFamily: 'Plus Jakarta Sans',
                    fontWeight: FontWeight.w500,
                    height: 1.60,
                    letterSpacing: -0.18,
                  ),
                ),
              ),
              Positioned(
                left: 29.09,
                top: 467,
                child: Text(
                  'Password',
                  style: TextStyle(
                    color: const Color(0xFF6C7278) /* Grey */,
                    fontSize: 9.18,
                    fontFamily: 'Plus Jakarta Sans',
                    fontWeight: FontWeight.w500,
                    height: 1.60,
                    letterSpacing: -0.18,
                  ),
                ),
              ),
              Positioned(
                left: 19.08,
                top: 176,
                child: SizedBox(
                  width: 225.57,
                  child: Text(
                    'Enter your email and password \nto log in ',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 11,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.40,
                      letterSpacing: -0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29.30,
                top: 413,
                child: Container(
                  width: 336.93,
                  height: 45.14,
                  padding: const EdgeInsets.symmetric(horizontal: 10.72, vertical: 20.67),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF2B5BD3),
                      ),
                      borderRadius: BorderRadius.circular(7.65),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3DE4E5E7),
                        blurRadius: 1.53,
                        offset: Offset(0, 0.77),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 7.65,
                    children: [
                      Expanded(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 9.18,
                          children: [
                            SizedBox(
                              width: 158.51,
                              height: 17.12,
                              child: Text(
                                'Loisbecket@gmail.com',
                                style: TextStyle(
                                  color: const Color(0xFF1A1C1E),
                                  fontSize: 10.72,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1.40,
                                  letterSpacing: -0.11,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 28.30,
                top: 484,
                child: Container(
                  width: 336.93,
                  height: 45.14,
                  padding: const EdgeInsets.symmetric(horizontal: 10.72, vertical: 20.67),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF2B5BD3),
                      ),
                      borderRadius: BorderRadius.circular(7.65),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3DE4E5E7),
                        blurRadius: 1.53,
                        offset: Offset(0, 0.77),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 7.65,
                    children: [
                      Expanded(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 9.18,
                          children: [
                            SizedBox(
                              width: 158.51,
                              height: 17.12,
                              child: Text(
                                '*************',
                                style: TextStyle(
                                  color: const Color(0xFF1A1C1E),
                                  fontSize: 10.72,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1.40,
                                  letterSpacing: -0.11,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 269.08,
                top: 536,
                child: Text(
                  'Forgot Password ?',
                  style: TextStyle(
                    color: const Color(0xFF25524A),
                    fontSize: 10,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                    letterSpacing: -0.10,
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 570,
                child: Container(
                  width: 336,
                  height: 50,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, 0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF6A9C89), const Color(0xFF16423C)],
                    ),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 345,
                child: Container(
                  width: 170,
                  height: 41,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, 0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF6A9C89)],
                    ),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 210,
                top: 345,
                child: Container(
                  width: 170,
                  height: 41,
                  decoration: ShapeDecoration(
                    color: const Color(0x4F4E5154),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 180,
                top: 586,
                child: Text(
                  'Log in',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 357,
                child: Text(
                  'Log in',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 270,
                top: 355,
                child: Text(
                  'Register',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 191,
                top: 638,
                child: Text(
                  'Or',
                  style: TextStyle(
                    color: const Color(0xFF6C7278),
                    fontSize: 10,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                    letterSpacing: -0.10,
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 646,
                child: Container(
                  width: 137,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 211,
                top: 646,
                child: Container(
                  width: 137,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 13,
                child: Container(
                  width: 22.31,
                  height: 23,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/22x23"),
                      fit: BoxFit.fill,
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 2.10,
                        offset: Offset(2, 3),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 17,
                child: Text(
                  'Smart Locker',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w800,
                    height: 1.40,
                    letterSpacing: -0.11,
                    shadows: [Shadow(offset: Offset(2, 3), blurRadius: 2, color: Color(0xFF000000).withOpacity(0.10))],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}