import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          OpenningScreen(),
        ]),
      ),
    );
  }
}

class OpenningScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 71,
                top: 546,
                child: Text(
                  'Explore the app',
                  style: TextStyle(
                    color: const Color(0xFF4D3E3E),
                    fontSize: 32,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.30,
                    letterSpacing: -0.32,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 599,
                child: SizedBox(
                  width: 319,
                  child: Text(
                    'Now your finances are in one place and always under control',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 178),
                      fontSize: 17,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 1.25,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 668,
                child: Container(
                  width: 336,
                  height: 50,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, 0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF6A9C89), const Color(0xFF16423C)],
                    ),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 177,
                top: 682,
                child: Text(
                  'Start ',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 1.40,
                    letterSpacing: -0.16,
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 150,
                child: Container(
                  width: 187.23,
                  height: 193,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/187x193"),
                      fit: BoxFit.fill,
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 2.10,
                        offset: Offset(2, 3),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 343,
                child: Text(
                  'Smart Locker',
                  style: TextStyle(
                    color: const Color(0xFF4D3E3E),
                    fontSize: 36,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w800,
                    height: 1.40,
                    letterSpacing: -0.36,
                    shadows: [Shadow(offset: Offset(2, 3), blurRadius: 2, color: Color(0xFF000000).withOpacity(0.10))],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}