import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ProfileUser(),
        ]),
      ),
    );
  }
}

class ProfileUser extends StatelessWidget {
  const ProfileUser({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 862,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.50, -0.00),
              end: Alignment(0.50, 1.00),
              colors: [const Color(0xFF50BF95), const Color(0xFF39705B)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -5,
                top: 0,
                child: Container(
                  width: 403,
                  height: 861,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: const Color(0xFFF9F9F9)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 5,
                        top: 102,
                        child: Container(
                          width: 393,
                          height: 788,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.50, -0.00),
                              end: Alignment(0.50, 1.00),
                              colors: [const Color(0xFF38A898), const Color(0xFF16423C)],
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(30),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x59000000),
                                blurRadius: 58.20,
                                offset: Offset(0, 0),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 188,
                        top: 710,
                        child: Container(
                          width: 22.31,
                          height: 23,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/22x23"),
                              fit: BoxFit.fill,
                            ),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x19000000),
                                blurRadius: 2.10,
                                offset: Offset(2, 3),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 162,
                        top: 735,
                        child: Text(
                          'Smart Locker',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 11,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w800,
                            height: 1.40,
                            letterSpacing: -0.11,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9,
                        top: 3,
                        child: SizedBox(
                          width: 375,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(width: 375, height: 44),
                              ),
                              Positioned(
                                left: 336,
                                top: 17.33,
                                child: Opacity(
                                  opacity: 0.35,
                                  child: Container(
                                    width: 22,
                                    height: 11.33,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1,
                                          color: const Color(0xFF181D27),
                                        ),
                                        borderRadius: BorderRadius.circular(2.67),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 338,
                                top: 19.33,
                                child: Container(
                                  width: 18,
                                  height: 7.33,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF181D27),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1.33),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 21,
                                top: 13,
                                child: SizedBox(
                                  width: 54,
                                  height: 21,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 3,
                                        child: SizedBox(
                                          width: 54,
                                          child: Text.rich(
                                            TextSpan(
                                              children: [
                                                TextSpan(
                                                  text: '9:4',
                                                  style: TextStyle(
                                                    color: const Color(0xFF181D27),
                                                    fontSize: 14,
                                                    fontFamily: 'SF Pro Display',
                                                    fontWeight: FontWeight.w500,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                                TextSpan(
                                                  text: '1',
                                                  style: TextStyle(
                                                    color: const Color(0xFF181D27),
                                                    fontSize: 14,
                                                    fontFamily: 'SF Pro Display',
                                                    fontWeight: FontWeight.w500,
                                                  ),
                                                ),
                                              ],
                                            ),
                                            textAlign: TextAlign.center,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 25,
                        top: 59,
                        child: Text(
                          'Language',
                          style: TextStyle(
                            color: const Color(0xFF181D27),
                            fontSize: 20,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w700,
                            height: 1.05,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 30,
                        top: 134,
                        child: Container(
                          width: 343,
                          height: 350,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(70),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: -5,
                                child: Container(
                                  width: 343,
                                  height: 566,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 17,
                                top: 27,
                                child: SizedBox(
                                  height: 49,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 25,
                                    children: [
                                      Container(
                                        transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                                        width: 15,
                                        height: 25,
                                        child: Stack(),
                                      ),
                                      Text(
                                        'Inggris',
                                        style: TextStyle(
                                          color: const Color(0xFF181D27),
                                          fontSize: 30,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w700,
                                          height: 0.65,
                                        ),
                                      ),
                                      Container(
                                        width: 40,
                                        height: 40,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF39705B),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                      SizedBox(width: 20, height: 20, child: Stack()),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 81,
                                child: Container(
                                  width: 316,
                                  height: 67,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF50BF95), const Color(0xFF386F5A)],
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 159,
                                child: Container(
                                  width: 316,
                                  height: 67,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF50BF95), const Color(0xFF386F5A)],
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 237,
                                child: Container(
                                  width: 316,
                                  height: 67,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF50BF95), const Color(0xFF386F5A)],
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 399,
                                child: Container(
                                  width: 316,
                                  height: 67,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF50BF95), const Color(0xFF386F5A)],
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 477,
                                child: Container(
                                  width: 316,
                                  height: 67,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF50BF95), const Color(0xFF386F5A)],
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 317,
                                child: Container(
                                  width: 316,
                                  height: 67,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF50BF95), const Color(0xFF386F5A)],
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0F000000),
                                        blurRadius: 44,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 132,
                        top: 749,
                        child: Text(
                          'No Keys, No Hassle, Just Click !',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w300,
                            height: 1.40,
                            letterSpacing: 0.56,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1,
                top: 812,
                child: Container(
                  width: 392,
                  height: 49,
                  decoration: BoxDecoration(
                    boxShadow: [
                      BoxShadow(
                        color: Color(0xBC000000),
                        blurRadius: 4,
                        offset: Offset(0, -1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 162.03,
                        top: 31,
                        child: Text(
                          'Transactions',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF555555),
                            fontSize: 10,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w400,
                            height: 1.30,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 182.93,
                        top: 10,
                        child: SizedBox(
                          width: 20.91,
                          height: 20,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 105.53,
                        top: 31,
                        child: Text(
                          'Card',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF555555),
                            fontSize: 10,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w400,
                            height: 1.30,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 105.58,
                        top: 10,
                        child: SizedBox(
                          width: 20.91,
                          height: 20,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 329.28,
                        top: 31,
                        child: Text(
                          'Profile',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF555555),
                            fontSize: 10,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w400,
                            height: 1.30,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 333.46,
                        top: 10,
                        child: SizedBox(
                          width: 20.91,
                          height: 20,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 252.93,
                        top: 30.94,
                        child: Text(
                          'Requests',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF555555),
                            fontSize: 10,
                            fontFamily: 'DM Sans',
                            fontWeight: FontWeight.w400,
                            height: 1.30,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 39,
                        top: 14,
                        child: SizedBox(width: 25, height: 25, child: Stack()),
                      ),
                      Positioned(
                        left: 48.95,
                        top: 37.75,
                        child: Container(
                          width: 11.96,
                          height: 1.25,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF204D45),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}